#!/usr/bin/env expect

#log_user 0
set stty_init "raw -echo"

set mode [lindex $argv 0]
set host [lindex $argv 1]
set chan [lindex $argv 2]

if {$mode == "tls"} {
    spawn openssl s_client -quiet -tls1_2 -connect $host:143 -starttls imap
} else {
    spawn openssl s_client -quiet -tls1_2 -connect $host:993
}
set server $spawn_id

expect {
    "* OK*\r\n" {
        send_user "Connected\n"
    }
    timeout {
        send_user "connect to $host timed out\n"
        exit
    }
    eof {
        send_user "EOF from $host\n"
        exit
    }
}

send ". CAPABILITY\r\n"
expect -re "\\* CAPABILITY (\[^\r\]+)\r\n"

set capability $expect_out(1,string)
regsub " LOGINDISABLED" $capability "" capability
regsub " IDLE" $capability "" capability
regsub -all " AUTH=\[^ \]+" $capability "" capability

spawn mbsync -q -q $chan
set client $spawn_id

send "* OK\r\n"

#expect {
#    -re "\n(\[^ \]+) CAPABILITY\r" {
#        send "* CAPABILITY $capability\r"
#        send "$expect_out(1,string) OK\r"
#    }
#}

interact -u $server
