#!/usr/bin/env expect

#log_user 0
set stty_init "raw -echo"
remove_nulls -d 0
parity -d 0

set mode [lindex $argv 0]
set host [lindex $argv 1]
set chan [lindex $argv 2]

set openssl_args "$host:143 -starttls imap"
if {$mode != "tls"} {
    set openssl_args "$host:993"
}

spawn /bin/sh -c "exec openssl s_client -quiet -tls1_2 -connect $openssl_args 2>/dev/null"
set server $spawn_id

if {$mode == "tls"} {
    send ". NOOP\r\n"
}

expect {
    "? OK*\r\n" {
        send_user "Connected\n"
    }
    timeout {
        send_user "connect to $host timed out\n"
        exit
    }
    eof {
        send_user "EOF from $host\n"
        exit
    }
}

spawn /bin/sh -c "exec mbsync -q -q $chan 2>/dev/null"
set client $spawn_id

send "* OK\r\n"

set capability ""
proc capability {server client} {
    interact -i $server -u $client -re "\\* CAPABILITY (\[^\r\]+)\r\n" {
        send -i $client -- $interact_out(0,string)

        set capability $interact_out(1,string)
        regsub " LOGINDISABLED" $capability "" capability
        regsub " IDLE" $capability "" capability
        regsub -all " AUTH=\[^ \]+" $capability "" capability

        return
    }
}

interact {
    -i $client -u $server
    -re "\[0-9\]\+ CAPABILITY\r\n" {
        send -i $server -- $interact_out(0,string)
        if {$capability == ""} {
            capability $server $client
        }
    }
    -re "(\[0-9\]\+) LOGOUT\r\n" {
        send -i $client "$interact_out(1,string) OK\r\n"
    }
}
